# Backtesting overlay that runs alongside data_ingester/ml_service/param_controller
services:
  backtest_runner:
    build:
      context: .
      dockerfile: services/backtest_suite/Dockerfile
    image: trading-app/backtest-runner:local
    env_file: [.env]
    environment:
      - LEDGER_DB=/research/manifest.sqlite
      - RESEARCH_DIR=/research
      - DATA_INCOMING=/research/incoming
      - ML_SERVICE=http://ml_service:8000
      - PARAM_CONTROLLER=http://param_controller:8002
      - CHUNK_ROWS=2000
      - TRAIN_CRON_MINUTES=360
      - EXACTLY_ONCE=false
      - TRAIN_MIN_POINTS=2000
      - FEE_BP=1.0
      - SLIPPAGE_BP=2.0
      - MAX_STEPS=1000
    depends_on:
      - ml_service
      - param_controller
    volumes:
      - research:/research
      - results:/results
    command: ["run"]

  research_scrubber:
    image: alpine:3.20
    container_name: hmm_research_scrubber
    command: ["/bin/sh","-c","crond -f -l 2"]
    volumes:
      - research:/research
      - ./ops/research_purge.cron:/etc/crontabs/root:ro
    restart: unless-stopped

volumes:
  research:
  results:
