# Full stack for continuous ingestion -> training -> param control
services:
  data_ingester:
    build:
      context: .
      dockerfile: services/data_ingester/Dockerfile
    image: trading-app/data-ingester:local
    environment:
      - LEDGER_DB=/shared/manifest.sqlite
      - DATA_LANDING=/data/incoming
      - EXCHANGE=binance
      - SYMBOLS=BTC/USDT,ETH/USDT
      - TIMEFRAME=1m
      - BATCH_LIMIT=1000
      - START_TS=0
    volumes:
      - data:/data
      - shared:/shared
    ports: ["8001:8001"]

  ml_service:
    build:
      context: .
      dockerfile: services/ml_service/Dockerfile
    image: trading-app/ml-service:local
    environment:
      - DATA_DIR=/data
      - REGISTRY_DIR=/models/registry
      - CURRENT_SYMLINK=/models/current
      - LEDGER_DB=/shared/manifest.sqlite
      - EXACTLY_ONCE=${ML_EXACTLY_ONCE:-true}
      - DELETE_AFTER_PROCESS=true
    depends_on:
      - data_ingester
    volumes:
      - data:/data
      - models:/models
      - shared:/shared
    ports: ["8003:8000"]

  ml_scheduler:
    image: trading-app/ml-service:local
    depends_on: [ml_service]
    command: ["python","-m","app.scheduler"]
    environment:
      - DATA_DIR=/data
      - REGISTRY_DIR=/models/registry
      - CURRENT_SYMLINK=/models/current
      - LEDGER_DB=/shared/manifest.sqlite
      - EXACTLY_ONCE=${ML_EXACTLY_ONCE:-true}
      - DELETE_AFTER_PROCESS=true
      - RETRAIN_CRON=0 */6 * * *
    volumes:
      - data:/data
      - models:/models
      - shared:/shared

  param_controller:
    build:
      context: .
      dockerfile: services/param_controller/Dockerfile
    image: trading-app/param-controller:local
    environment:
      - PC_DB=/shared/param_controller.sqlite
    volumes:
      - shared:/shared
    ports: ["8002:8002"]

volumes:
  data:
  models:
  shared:
