services:
  data_backfill:
    build:
      context: .
      dockerfile: services/data_ingester/Dockerfile
    image: trading-app/data-backfill:local
    env_file:
      - .env
    environment:
      - EXCHANGE=binance
      - SYMBOLS=BTC/USDT,ETH/USDT
      - TIMEFRAME=1m
      - BATCH_LIMIT=1000
      - START_TS=0
      - END_TS=0
      - SLEEP_MS=500
    command: ["python", "-m", "app.backfill"]
    volumes:
      - data:/data
      - shared:/shared

volumes:
  data:
  shared:
