from __future__ import annotations

from typing import Any, Dict


def _merge_dicts(*sources: Dict[str, Any]) -> Dict[str, Any]:
    merged: Dict[str, Any] = {}
    for src in sources:
        merged.update(src)
    return merged


ENGINE_DEFAULTS: Dict[str, Any] = {
    "EVENTBUS_MAX_WORKERS": 8,
}

GLOBAL_DEFAULTS: Dict[str, Any] = {
    "TRADE_SYMBOLS": "*",
    "DRY_RUN": True,
}

RISK_DEFAULTS: Dict[str, Any] = {
    "TRADING_ENABLED": False,
    "MIN_NOTIONAL_USDT": 10.0,
    "MAX_NOTIONAL_USDT": 1000.0,
    "MAX_ORDERS_PER_MIN": 30,
    "DUST_THRESHOLD_USD": 2.0,
    "EXPOSURE_CAP_SYMBOL_USD": 2000.0,
    "EXPOSURE_CAP_TOTAL_USD": 10000.0,
    "EXPOSURE_CAP_VENUE_USD": 10000.0,
    "VENUE_ERROR_BREAKER_PCT": 50.0,
    "VENUE_ERROR_WINDOW_SEC": 60,
    "EQUITY_FLOOR_USD": 500.0,
    "EQUITY_DRAWDOWN_LIMIT_PCT": 35.0,
    "EQUITY_COOLDOWN_SEC": 300,
    "MARGIN_ENABLED": False,
    "MARGIN_MIN_LEVEL": 1.2,
    "MARGIN_MAX_LIABILITY_USD": 25000.0,
    "MARGIN_MAX_LEVERAGE": 3.0,
    "OPTIONS_ENABLED": False,
    "SOFT_BREACH_ENABLED": True,
    "SOFT_BREACH_TIGHTEN_SL_PCT": 0.6,
    "SOFT_BREACH_BREAKEVEN_OK": True,
    "SOFT_BREACH_CANCEL_ENTRIES": True,
    "SOFT_BREACH_LOG_ORDERS": True,
}

TREND_DEFAULTS: Dict[str, Any] = {
    "TREND_ENABLED": False,
    "TREND_DRY_RUN": True,
    "TREND_SYMBOLS": "",
    "TREND_FETCH_LIMIT": 720,
    "TREND_REFRESH_SEC": 15 * 60,
    "TREND_ATR_LENGTH": 14,
    "TREND_ATR_STOP_MULT": 1.2,
    "TREND_ATR_TARGET_MULT": 2.0,
    "TREND_SWING_LOOKBACK": 3,
    "TREND_RSI_LONG_MIN": 52.0,
    "TREND_RSI_LONG_MAX": 72.0,
    "TREND_RSI_EXIT": 80.0,
    "TREND_RISK_PCT": 0.015,
    "TREND_MIN_QUOTE_USD": 75.0,
    "TREND_FALLBACK_EQUITY": 2000.0,
    "TREND_COOLDOWN_BARS": 3,
    "TREND_ALLOW_SHORTS": False,
    "TREND_AUTO_TUNE_ENABLED": False,
    "TREND_AUTO_TUNE_MIN_TRADES": 30,
    "TREND_AUTO_TUNE_INTERVAL": 15,
    "TREND_AUTO_TUNE_HISTORY": 200,
    "TREND_AUTO_TUNE_WIN_LOW": 0.4,
    "TREND_AUTO_TUNE_WIN_HIGH": 0.65,
    "TREND_AUTO_TUNE_STOP_MIN": 0.5,
    "TREND_AUTO_TUNE_STOP_MAX": 2.5,
    "TREND_AUTO_TUNE_STATE_PATH": "data/runtime/trend_auto_tune.json",
    "TREND_PRIMARY_INTERVAL": "4h",
    "TREND_PRIMARY_FAST": 50,
    "TREND_PRIMARY_SLOW": 200,
    "TREND_PRIMARY_RSI": 14,
    "TREND_SECONDARY_INTERVAL": "1h",
    "TREND_SECONDARY_FAST": 100,
    "TREND_SECONDARY_SLOW": 400,
    "TREND_SECONDARY_RSI": 14,
    "TREND_REGIME_INTERVAL": "1d",
    "TREND_REGIME_FAST": 50,
    "TREND_REGIME_SLOW": 200,
    "TREND_REGIME_RSI": 14,
}

SCALP_DEFAULTS: Dict[str, Any] = {
    "SCALP_ENABLED": False,
    "SCALP_DRY_RUN": True,
    "SCALP_SYMBOLS": "",
    "SCALP_WINDOW_SEC": 30.0,
    "SCALP_MIN_TICKS": 8,
    "SCALP_MIN_RANGE_BPS": 6.0,
    "SCALP_LOWER_THRESHOLD": 0.22,
    "SCALP_UPPER_THRESHOLD": 0.78,
    "SCALP_RSI_LENGTH": 2,
    "SCALP_RSI_BUY": 20.0,
    "SCALP_RSI_SELL": 80.0,
    "SCALP_STOP_BPS": 12.0,
    "SCALP_TP_BPS": 18.0,
    "SCALP_QUOTE_USD": 125.0,
    "SCALP_COOLDOWN_SEC": 15.0,
    "SCALP_ALLOW_SHORTS": True,
    "SCALP_PREFER_FUTURES": True,
    "SCALP_SIGNAL_TTL_SEC": 30.0,
    "SCALP_MAX_SIGNALS_PER_MIN": 6,
    "SCALP_IMBALANCE_THRESHOLD": 0.18,
    "SCALP_MAX_SPREAD_BPS": 6.0,
    "SCALP_MIN_DEPTH_USD": 20000.0,
    "SCALP_MOMENTUM_TICKS": 3,
    "SCALP_FEE_BPS": 7.5,
    "SCALP_BOOK_STALE_SEC": 5.0,
}

MOMENTUM_RT_DEFAULTS: Dict[str, Any] = {
    "MOMENTUM_RT_ENABLED": False,
    "MOMENTUM_RT_DRY_RUN": True,
    "MOMENTUM_RT_SYMBOLS": "",
    "MOMENTUM_RT_WINDOW_SEC": 45.0,
    "MOMENTUM_RT_BASELINE_SEC": 6 * 60.0,
    "MOMENTUM_RT_MOVE_THRESHOLD_PCT": 1.8,
    "MOMENTUM_RT_VOLUME_SPIKE_RATIO": 2.0,
    "MOMENTUM_RT_STOP_PCT": 0.8,
    "MOMENTUM_RT_TRAIL_PCT": 1.2,
    "MOMENTUM_RT_TP_PCT": 3.5,
    "MOMENTUM_RT_MIN_TICKS": 3,
    "MOMENTUM_RT_COOLDOWN_SEC": 180.0,
    "MOMENTUM_RT_QUOTE_USD": 150.0,
    "MOMENTUM_RT_ALLOW_SHORTS": False,
    "MOMENTUM_RT_PREFER_FUTURES": True,
}

MEME_SENTIMENT_DEFAULTS: Dict[str, Any] = {
    "MEME_SENTIMENT_ENABLED": False,
    "MEME_SENTIMENT_DRY_RUN": True,
    "MEME_SENTIMENT_RISK_PCT": 0.0075,
    "MEME_SENTIMENT_STOP_PCT": 0.10,
    "MEME_SENTIMENT_TP_PCT": 0.25,
    "MEME_SENTIMENT_TRAIL_PCT": 0.12,
    "MEME_SENTIMENT_FALLBACK_EQUITY": 2000.0,
    "MEME_SENTIMENT_NOTIONAL_MIN": 25.0,
    "MEME_SENTIMENT_NOTIONAL_MAX": 200.0,
    "MEME_SENTIMENT_MIN_PRIORITY": 0.82,
    "MEME_SENTIMENT_MIN_SCORE": 2.2,
    "MEME_SENTIMENT_MIN_MENTIONS": 18,
    "MEME_SENTIMENT_MIN_VELOCITY": 1.0,
    "MEME_SENTIMENT_MAX_CHASE_PCT": 0.55,
    "MEME_SENTIMENT_MAX_SPREAD_PCT": 0.035,
    "MEME_SENTIMENT_COOLDOWN_SEC": 1200.0,
    "MEME_SENTIMENT_LOCK_SEC": 600.0,
    "MEME_SENTIMENT_DENY_KEYWORDS": "rug,rugpull,scam,honeypot",
    "MEME_SENTIMENT_SOURCES": "twitter_firehose,dex_whale,binance_listings",
    "MEME_SENTIMENT_QUOTES": "USDT,USDC,BUSD",
    "MEME_SENTIMENT_METRICS_ENABLED": True,
    "MEME_SENTIMENT_PUBLISH_TOPIC": "strategy.meme_sentiment_trade",
    "MEME_SENTIMENT_DEFAULT_MARKET": "spot",
    "SOCIAL_SENTIMENT_ENABLED": False,
    "SOCIAL_SENTIMENT_SOURCES": "",
}

SYMBOL_SCANNER_DEFAULTS: Dict[str, Any] = {
    "SYMBOL_SCANNER_ENABLED": False,
    "SYMBOL_SCANNER_UNIVERSE": "TOP_50_BY_VOLUME",
    "SYMBOL_SCANNER_INTERVAL_SEC": 300,
    "SYMBOL_SCANNER_INTERVAL": "1h",
    "SYMBOL_SCANNER_LOOKBACK": 60,
    "SYMBOL_SCANNER_TOP_N": 3,
    "SYMBOL_SCANNER_MIN_VOLUME_USD": 250_000.0,
    "SYMBOL_SCANNER_MIN_ATR_PCT": 0.5,
    "SYMBOL_SCANNER_WEIGHT_RET": 0.5,
    "SYMBOL_SCANNER_WEIGHT_TREND": 0.3,
    "SYMBOL_SCANNER_WEIGHT_VOL": 0.2,
    "SYMBOL_SCANNER_MIN_MINUTES_BETWEEN_RESELECT": 30,
    "SYMBOL_SCANNER_STATE_PATH": "data/runtime/symbol_scanner_state.json",
}

BROKER_DEFAULTS: Dict[str, Any] = {
    "IBKR_ENABLED": False,
}

AUTOTRAIN_SHARED_DEFAULTS: Dict[str, Any] = {
    "LEDGER_DB": "/shared/manifest.sqlite",
}

DATA_INGESTER_DEFAULTS: Dict[str, Any] = {
    "DATA_LANDING": "/data/incoming",
    "EXCHANGE": "binance",
    "SYMBOLS": "BTC/USDT,ETH/USDT",
    "TIMEFRAME": "1m",
    "BATCH_LIMIT": 1000,
    "START_TS": 0,
    "LOG_LEVEL": "INFO",
}

ML_SERVICE_DEFAULTS: Dict[str, Any] = {
    "DATA_DIR": "/data",
    "MODEL_DIR": "/models",
    "REGISTRY_DIR": "/models/registry",
    "CURRENT_SYMLINK": "/models/current",
    "HMM_STATES": 4,
    "TRAIN_WINDOW_DAYS": 365,
    "EXACTLY_ONCE": False,
    "TRAIN_MIN_POINTS": 2000,
    "PROMOTION_MIN_DELTA": 1.0,
    "KEEP_N_MODELS": 5,
    "AUTO_PROMOTE": True,
    "DELETE_AFTER_PROCESS": True,
    "RETRAIN_CRON": "0 */6 * * *",
    "REQUIRE_AUTH": False,
    "JWT_ALG": "HS256",
    "JWT_SECRET": "",
    "JWT_PUBLIC_KEY": "",
    "LOG_LEVEL": "INFO",
}

PARAM_CONTROLLER_DEFAULTS: Dict[str, Any] = {
    "PC_DB": "/shared/param_controller.sqlite",
    "EPSILON": 0.05,
    "L2": 1.0,
    "MAX_PRESETS": 12,
    "LOG_LEVEL": "INFO",
}

BACKTEST_RUNNER_DEFAULTS: Dict[str, Any] = {
    "RESEARCH_DIR": "/research",
    "DATA_INCOMING": "/data/incoming",
    "ML_SERVICE": "http://ml_service:8000",
    "PARAM_CONTROLLER": "http://param_controller:8002",
    "SYMBOLS": "BTC/USDT,ETH/USDT",
    "TIMEFRAME": "1m",
    "CHUNK_ROWS": 1000,
    "START_TS": 0,
    "END_TS": 0,
    "TRAIN_CRON_MINUTES": 360,
    "PROMOTE": True,
    "EXACTLY_ONCE": False,
    "TRAIN_MIN_POINTS": 2000,
    "FEE_BP": 1.0,
    "SLIPPAGE_BP": 2.0,
    "MAX_STEPS": 100000,
    "LOG_LEVEL": "INFO",
}

ALL_DEFAULTS: Dict[str, Any] = _merge_dicts(
    ENGINE_DEFAULTS,
    GLOBAL_DEFAULTS,
    RISK_DEFAULTS,
    TREND_DEFAULTS,
    SCALP_DEFAULTS,
    MOMENTUM_RT_DEFAULTS,
    MEME_SENTIMENT_DEFAULTS,
    SYMBOL_SCANNER_DEFAULTS,
    BROKER_DEFAULTS,
    AUTOTRAIN_SHARED_DEFAULTS,
    DATA_INGESTER_DEFAULTS,
    ML_SERVICE_DEFAULTS,
    PARAM_CONTROLLER_DEFAULTS,
    BACKTEST_RUNNER_DEFAULTS,
)

__all__ = [
    "ENGINE_DEFAULTS",
    "GLOBAL_DEFAULTS",
    "RISK_DEFAULTS",
    "TREND_DEFAULTS",
    "SCALP_DEFAULTS",
    "MOMENTUM_RT_DEFAULTS",
    "MEME_SENTIMENT_DEFAULTS",
    "SYMBOL_SCANNER_DEFAULTS",
    "AUTOTRAIN_SHARED_DEFAULTS",
    "DATA_INGESTER_DEFAULTS",
    "ML_SERVICE_DEFAULTS",
    "PARAM_CONTROLLER_DEFAULTS",
    "BACKTEST_RUNNER_DEFAULTS",
    "ALL_DEFAULTS",
]
